---
- name: Aptitude Tasks - Include distribution-specific variables
  include_vars: "packages.yml"

- name: Aptitude Tasks - Upgrade all packages
  apt:
    upgrade: "yes"
    update_cache: true
    cache_valid_time: 604800  # 1 Week.

- name: Aptitude Tasks - Install required packages
  apt:
    name: "{{ packages }}"
    state: present

- name: Aptitude Tasks - Remove dependencies that are no longer required
  apt:
    autoremove: true
